### ISSUE TITLE
 Navigation case not resolved for component

### ISSUE THREAD

**Issue by rammygit** [rammygit/teamreport#4]
12:09:10,535 WARNING [javax.enterprise.resource.webcontainer.jsf.renderkit](default task-28) JSF1090: Navigation case not resolved for component j_idt19.
12:09:16,073 WARNING [javax.enterprise.resource.webcontainer.jsf.renderkit](default task-33) JSF1090: Navigation case not resolved for component j_idt70.
12:09:40,612 WARNING [javax.enterprise.resource.webcontainer.jsf.renderkit](default task-39) JSF1090: Navigation case not resolved for component j_idt70.
12:11:02,407 WARNING [javax.enterprise.resource.webcontainer.jsf.renderkit](default task-58) JSF1090: Navigation case not resolved for component j_idt70.

Added new navigation case and it is not resolved.

**Comment by dhruvalvaishnav** [comment]
In this case, review your application files and check if the target I mean outcome attribute really exists and is declared correctly.
I solved that by changing the names of the outcome attribute.
Thanks 
Good luck 👍🏻
